blank_issues_enabled: false
contact_links:
  - name: testCT.jl package support
    url: https://github.com/remydutto/testCT.jl/discussions
    about: Please ask and answer questions about testCT.jl here.
  - name: Control-toolbox organisation support
    url: https://github.com/orgs/control-toolbox/discussions
    about: For more general questions about control-toolbox ecosystem it's here.
